name: Simulator tests
on:
  push:
    branches:
      - master
  schedule:
    - cron: "17 * * * *" # Hourly
  workflow_dispatch:
    inputs:
      run_on_ghrunners:
        description: "Also run on GitHub-hosted runners"
        required: false
        type: boolean

permissions:
  contents: read
  id-token: write # This is required for requesting the JWT

jobs:
  resolve:
    runs-on:
      - namespace-profile-macos-default
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Resolve
        run: |
          xcodebuild -resolvePackageDependencies -scheme SIP -project ./SIP.xcodeproj
  fastlane:
    runs-on:
      - namespace-profile-macos-default
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fastlane
        run: |
          fastlane screenshots
  test:
    runs-on:
      - namespace-profile-macos-default
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          xcodebuild test -quiet -scheme SIP -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2'

  test-ghrunners:
    if: inputs.run_on_ghrunners
    runs-on:
      - macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          fastlane screenshots
          xcodebuild test -quiet -scheme SIP -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2'
