name: Simulator tests
on:
  push:
    branches:
      - master
  schedule:
    - cron: "17 * * * *" # Hourly
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # This is required for requesting the JWT

jobs:
  test:
    runs-on:
      - namespace-profile-macos-default
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          xcodebuild test -quiet -scheme SIP -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2'
