name: Simulator tests
on:
  push:
    branches:
      - master
  schedule:
    - cron: "17 * * * *" # Hourly
  workflow_dispatch:
    inputs:
      run_on_ghrunners:
        description: "Also run on GitHub-hosted runners"
        required: false
        type: boolean

jobs:
  fastlane:
    runs-on: namespace-profile-macos-default
    steps:
      - uses: actions/checkout@v4
      - run: |
          fastlane screenshots

  test:
    runs-on: namespace-profile-macos-default
    steps:
      - uses: actions/checkout@v4
      - run: |
          xcodebuild test -quiet -scheme SIP -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2'

  test-ghrunners:
    runs-on: macos-12
    if: inputs.run_on_ghrunners
    steps:
      - uses: actions/checkout@v4
      - run: |
          xcodebuild test -quiet -scheme SIP -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2'
